import type {
  Building,
  Research,
  Expedition,
  Resource,
  Cost,
  Recipe,
  EventDef,
} from "./types";
export const resources: {
  id: Resource;
  name: string;
  group: string;
  icon: string;
  unlock?: string;
}[] = [
  ["wood", "Drewno", "Drewno", "log"],
  ["hardwood", "Twarde drewno", "Drewno", "hardlog", "forestry"],
  ["noblewood", "Szlachetne drewno", "Drewno", "noblelog", "carpentry"],
  ["planks", "Deski", "Drewno", "plank", "sawing"],
  ["hardplanks", "Twarde deski", "Drewno", "hardplank", "forestry"],
  ["nobleplanks", "Szlachetne deski", "Drewno", "nobleplank", "carpentry"],
  ["stone", "Kamień", "Materiały", "stone"],
  ["bricks", "Cegły kamienne", "Materiały", "brick", "masonry"],
  ["clay", "Glina", "Materiały", "copperore", "pottery"],
  ["pottery", "Naczynia", "Materiały", "food", "pottery"],
  ["ironore", "Ruda żelaza", "Rudy i metale", "ore", "ironwork"],
  ["copperore", "Ruda miedzi", "Rudy i metale", "copperore", "mining"],
  ["tinore", "Ruda cyny", "Rudy i metale", "tinore", "tin"],
  ["charcoal", "Węgiel drzewny", "Rudy i metale", "coal", "charcoal"],
  ["coal", "Węgiel kamienny", "Rudy i metale", "coal", "ironwork"],
  ["iron", "Żelazo", "Rudy i metale", "ingot", "ironwork"],
  ["copper", "Miedź", "Rudy i metale", "copper", "copperwork"],
  ["bronze", "Brąz", "Rudy i metale", "bronze", "bronzework"],
  ["food", "Jedzenie", "Zapasy", "food"],
  ["water", "Woda", "Zapasy", "water"],
  ["leather", "Skóry", "Zapasy", "hide", "hunting"],
  ["flax", "Len", "Zapasy", "farm", "agriculture"],
  ["cloth", "Tkaniny", "Zapasy", "cloth", "weaving"],
  ["rope", "Liny", "Zapasy", "log", "weaving"],
  ["grain", "Zboże", "Zapasy", "farm", "agriculture"],
  ["flour", "Mąka", "Zapasy", "food", "milling"],
  ["herbs", "Zioła", "Zapasy", "farm", "herbalism"],
  ["medicine", "Medykamenty", "Zapasy", "water", "herbalism"],
  ["stoneTools", "Narzędzia kamienne", "Wyposażenie", "tools", "stonecraft"],
  ["bronzeTools", "Narzędzia z brązu", "Wyposażenie", "tools", "bronzework"],
  ["tools", "Narzędzia żelazne", "Wyposażenie", "tools", "ironwork"],
  ["packs", "Plecaki", "Wyposażenie", "hide", "packing"],
  ["maps", "Mapy", "Znaleziska", "book", "scouting"],
  ["seeds", "Nasiona", "Znaleziska", "farm", "scouting"],
  ["relics", "Relikty", "Znaleziska", "bronze", "cartography"],
  ["gold", "Złoto", "Znaleziska", "bronze", "trade"],
  ["knowledge", "Wiedza", "Znaleziska", "book", "learning"],
].map(([id, name, group, icon, unlock]) => ({
  id: id as Resource,
  name,
  group,
  icon,
  unlock,
}));
const r = (
  id: string,
  name: string,
  input: Cost,
  output: Cost,
  research?: string,
  tool = false,
  minTool?: Recipe["minTool"],
): Recipe => ({ id, name, input, output, research, tool, minTool });
const b = (
  id: string,
  name: string,
  icon: string,
  group: string,
  description: string,
  cost: Cost,
  recipes: Recipe[],
  research?: string,
  housing?: number,
  duration = 25,
): Building => ({
  id,
  name,
  icon,
  group,
  description,
  cost,
  recipes,
  research,
  housing,
  duration,
});
// Wszystkie receptury podają ilości na pracownika i JEDEN TIK (sekundę).
export const buildings: Building[] = [
  b(
    "gatherers",
    "Zbieracze",
    "person",
    "Pozyskiwanie",
    "Ręczne zbieranie zasobów. Każdy wiersz ma własny przydział ludzi.",
    { wood: 15, stone: 8 },
    [
      r("wood", "Gałęzie", {}, { wood: 0.18 }),
      r("stone", "Luźne kamienie", {}, { stone: 0.14 }),
      r("food", "Jagody", {}, { food: 0.18 }),
      r("water", "Woda ze strumienia", {}, { water: 0.2 }),
      r("clay", "Glina", {}, { clay: 0.12 }, "pottery"),
      r("herbs", "Zioła", {}, { herbs: 0.08 }, "herbalism"),
    ],
  ),
  b(
    "fire",
    "Palenisko",
    "fire",
    "Mieszkania",
    "Każdy poziom powyżej pierwszego daje +5% tempa pracy.",
    { wood: 35, stone: 20 },
    [],
  ),
  b(
    "shelter",
    "Szałasy",
    "tent",
    "Mieszkania",
    "Każdy poziom daje miejsce 3 mieszkańcom.",
    { wood: 25, stone: 8 },
    [],
    "shelters",
    3,
  ),
  b(
    "house",
    "Domy z kłód",
    "house",
    "Mieszkania",
    "Każdy poziom daje miejsce 5 mieszkańcom.",
    { wood: 70, stone: 35 },
    [],
    "loghomes",
    5,
    45,
  ),
  b(
    "boardhouse",
    "Domy z desek",
    "house",
    "Mieszkania",
    "Każdy poziom daje miejsce 8 mieszkańcom.",
    { planks: 45, stone: 30, rope: 8 },
    [],
    "housing",
    8,
    70,
  ),
  b(
    "stonehouse",
    "Domy kamienne",
    "house",
    "Mieszkania",
    "Każdy poziom daje miejsce 12 mieszkańcom.",
    { bricks: 65, hardplanks: 35, tools: 3 },
    [],
    "architecture",
    12,
    100,
  ),
  b(
    "logger",
    "Chata drwala",
    "logger",
    "Pozyskiwanie",
    "Rozdziel drwali pomiędzy gatunki drewna. Trudniejsze gatunki wymagają wyposażenia.",
    { wood: 25, stone: 15 },
    [
      r("wood", "Drewno", {}, { wood: 0.35 }, undefined, true, "stoneTools"),
      r(
        "hardwood",
        "Twarde drewno",
        {},
        { hardwood: 0.17 },
        "forestry",
        true,
        "stoneTools",
      ),
      r(
        "noblewood",
        "Szlachetne drewno",
        {},
        { noblewood: 0.09 },
        "carpentry",
        true,
        "bronzeTools",
      ),
    ],
    "logging",
  ),
  b(
    "quarry",
    "Kamieniarz",
    "quarry",
    "Pozyskiwanie",
    "Kamień oraz kamienne cegły. Narzędzia przyspieszają oba zadania.",
    { wood: 30, stone: 20 },
    [
      r("stone", "Kamień", {}, { stone: 0.28 }, undefined, true, "stoneTools"),
      r(
        "bricks",
        "Kamienne cegły",
        { stone: 0.3 },
        { bricks: 0.12 },
        "masonry",
        true,
        "stoneTools",
      ),
    ],
    "quarrying",
  ),
  b(
    "well",
    "Studnia",
    "well",
    "Pozyskiwanie",
    "Wydajny dostęp do czystej wody.",
    { wood: 25, stone: 40 },
    [r("water", "Woda", {}, { water: 0.55 })],
    "waterworks",
  ),
  b(
    "hunter",
    "Chata łowcy",
    "tent",
    "Pozyskiwanie",
    "Polowania dostarczają żywność i skóry.",
    { wood: 35, stoneTools: 2 },
    [
      r(
        "hunt",
        "Polowanie",
        {},
        { food: 0.22, leather: 0.08 },
        undefined,
        true,
        "stoneTools",
      ),
    ],
    "hunting",
  ),
  b(
    "farm",
    "Gospodarstwo",
    "farm",
    "Pozyskiwanie",
    "Równoczesna uprawa żywności, zboża i lnu.",
    { wood: 50, stone: 25, seeds: 2 },
    [
      r("food", "Warzywa", {}, { food: 0.4 }, undefined, true),
      r("grain", "Zboże", {}, { grain: 0.25 }, undefined, true),
      r("flax", "Len", {}, { flax: 0.2 }, undefined, true),
    ],
    "agriculture",
  ),
  b(
    "mine",
    "Kopalnia",
    "mine",
    "Pozyskiwanie",
    "Osobny przydział górników dla każdego złoża.",
    { planks: 30, stone: 40, rope: 5 },
    [
      r(
        "copperore",
        "Ruda miedzi",
        {},
        { copperore: 0.18 },
        undefined,
        true,
        "stoneTools",
      ),
      r("tinore", "Ruda cyny", {}, { tinore: 0.12 }, "tin", true, "stoneTools"),
      r(
        "ironore",
        "Ruda żelaza",
        {},
        { ironore: 0.16 },
        "ironwork",
        true,
        "bronzeTools",
      ),
      r(
        "coal",
        "Węgiel kamienny",
        {},
        { coal: 0.2 },
        "ironwork",
        true,
        "bronzeTools",
      ),
    ],
    "mining",
  ),
  b(
    "workshop",
    "Warsztat narzędzi",
    "tools",
    "Przetwarzanie",
    "Narzędzia powstają z drewna i kamienia. Pełne komplety przydzielasz pracownikom.",
    { wood: 15, stone: 10 },
    [
      r(
        "stoneTools",
        "Narzędzia kamienne",
        { wood: 0.16, stone: 0.2 },
        { stoneTools: 0.025 },
      ),
    ],
    "stonecraft",
  ),
  b(
    "sawmill",
    "Tartak",
    "sawmill",
    "Przetwarzanie",
    "Każdy rodzaj desek ma własny zespół, limit i przełącznik produkcji.",
    { wood: 45, stone: 25, stoneTools: 2 },
    [
      r("planks", "Deski", { wood: 0.5 }, { planks: 0.25 }, undefined, true),
      r(
        "hardplanks",
        "Twarde deski",
        { hardwood: 0.3 },
        { hardplanks: 0.15 },
        "forestry",
        true,
      ),
      r(
        "nobleplanks",
        "Szlachetne deski",
        { noblewood: 0.2 },
        { nobleplanks: 0.1 },
        "carpentry",
        true,
      ),
    ],
    "sawing",
  ),
  b(
    "kiln",
    "Piece i smolarnia",
    "kiln",
    "Przetwarzanie",
    "Węgiel drzewny i ceramika powstają niezależnie.",
    { stone: 40, wood: 35 },
    [
      r("charcoal", "Węgiel drzewny", { wood: 0.35 }, { charcoal: 0.18 }),
      r(
        "pottery",
        "Naczynia",
        { clay: 0.25, wood: 0.1 },
        { pottery: 0.1 },
        "pottery",
      ),
    ],
    "charcoal",
  ),
  b(
    "weaver",
    "Tkacz i powroźnik",
    "weaver",
    "Przetwarzanie",
    "Z lnu wytwarza tkaniny i liny.",
    { planks: 25, wood: 20 },
    [
      r("cloth", "Tkaniny", { flax: 0.3 }, { cloth: 0.12 }),
      r("rope", "Liny", { flax: 0.2 }, { rope: 0.1 }),
    ],
    "weaving",
  ),
  b(
    "mill",
    "Młyn i piekarnia",
    "farm",
    "Przetwarzanie",
    "Zboże na mąkę, a mąka i woda na żywność.",
    { planks: 35, stone: 50 },
    [
      r("flour", "Mąka", { grain: 0.35 }, { flour: 0.28 }),
      r("bread", "Chleb", { flour: 0.25, water: 0.1 }, { food: 0.65 }),
    ],
    "milling",
  ),
  b(
    "smelter",
    "Huta",
    "smelter",
    "Przetwarzanie",
    "Równolegle przetapia miedź, brąz i żelazo.",
    { bricks: 30, planks: 25 },
    [
      r(
        "copper",
        "Miedź",
        { copperore: 0.3, charcoal: 0.15 },
        { copper: 0.15 },
      ),
      r(
        "bronze",
        "Brąz",
        { copper: 0.2, tinore: 0.1, charcoal: 0.1 },
        { bronze: 0.2 },
        "bronzework",
      ),
      r(
        "iron",
        "Żelazo",
        { ironore: 0.3, coal: 0.15 },
        { iron: 0.15 },
        "ironwork",
      ),
    ],
    "copperwork",
  ),
  b(
    "smith",
    "Kuźnia",
    "smith",
    "Przetwarzanie",
    "Wytwarza lepsze komplety narzędzi dla pracowników.",
    { bricks: 25, planks: 30 },
    [
      r(
        "bronzeTools",
        "Narzędzia z brązu",
        { bronze: 0.2, wood: 0.1 },
        { bronzeTools: 0.025 },
      ),
      r(
        "tools",
        "Narzędzia żelazne",
        { iron: 0.2, hardwood: 0.1 },
        { tools: 0.025 },
        "ironwork",
      ),
    ],
    "bronzework",
  ),
  b(
    "outfitter",
    "Warsztat podróżnika",
    "warehouse",
    "Przetwarzanie",
    "Plecaki zwiększają łupy wypraw; medykamenty są potrzebne do odległych ruin.",
    { planks: 25, leather: 10 },
    [
      r("packs", "Plecaki", { leather: 0.2, cloth: 0.1 }, { packs: 0.02 }),
      r(
        "medicine",
        "Medykamenty",
        { herbs: 0.25, water: 0.1 },
        { medicine: 0.05 },
        "herbalism",
      ),
    ],
    "packing",
  ),
  b(
    "warehouse",
    "Magazyn",
    "warehouse",
    "Zaplecze",
    "Każdy poziom daje +200 pojemności zasobów. Złoto nie zajmuje magazynu.",
    { wood: 45, stone: 25 },
    [],
    "storage",
  ),
  b(
    "library",
    "Pracownia",
    "library",
    "Zaplecze",
    "Wytwarza wiedzę i mapy potrzebne do dalszych odkryć.",
    { planks: 30, cloth: 10 },
    [
      r("knowledge", "Wiedza", {}, { knowledge: 0.12 }),
      r(
        "maps",
        "Mapy",
        { knowledge: 0.15, cloth: 0.05 },
        { maps: 0.015 },
        "cartography",
      ),
    ],
    "learning",
  ),
  b(
    "camp",
    "Obóz zwiadowców",
    "tent",
    "Zaplecze",
    "Otwiera wyprawy. Kolejne poziomy skracają podróż o 5%, do 25%.",
    { wood: 35, food: 20 },
    [],
    "scouting",
  ),
];
const d = (
  id: string,
  name: string,
  icon: string,
  branch: string,
  description: string,
  requires: string[],
  cost: Cost,
  duration = 40,
): Research => ({
  id,
  name,
  icon,
  branch,
  description,
  requires,
  cost,
  duration,
  kind: "research",
});
export const researches: Research[] = [
  d(
    "stonecraft",
    "Narzędzia kamienne",
    "tools",
    "Rzemiosło",
    "Odblokowuje warsztat i narzędzia z drewna oraz kamienia.",
    [],
    { wood: 12, stone: 12 },
    15,
  ),
  d(
    "logging",
    "Drwal",
    "logger",
    "Rzemiosło",
    "Odblokowuje chatę drwala. Każdy drwal potrzebuje narzędzi.",
    ["stonecraft"],
    { wood: 20, stoneTools: 1 },
    20,
  ),
  d(
    "quarrying",
    "Kamieniarz",
    "quarry",
    "Rzemiosło",
    "Odblokowuje wydajne pozyskiwanie kamienia.",
    ["stonecraft"],
    { stone: 20, stoneTools: 1 },
    20,
  ),
  d(
    "sawing",
    "Piłowanie drewna",
    "sawmill",
    "Rzemiosło",
    "Odblokowuje tartak i deski.",
    ["logging", "loghomes"],
    { wood: 45, stoneTools: 2 },
  ),
  d(
    "forestry",
    "Twarde drewno",
    "hardlog",
    "Rzemiosło",
    "Pozyskiwanie twardego drewna i wytwarzanie twardych desek.",
    ["sawing"],
    { planks: 30, stoneTools: 3 },
    60,
  ),
  d(
    "carpentry",
    "Szlachetne drewno",
    "noblelog",
    "Rzemiosło",
    "Szlachetne drewno i deski. Wycinka wymaga narzędzi z brązu lub żelaza.",
    ["forestry", "bronzework"],
    { hardplanks: 35, knowledge: 25 },
    90,
  ),
  d(
    "shelters",
    "Szałasy",
    "tent",
    "Budownictwo",
    "Pierwsze schronienia: +3 miejsca na poziom.",
    [],
    { wood: 15, stone: 5 },
    15,
  ),
  d(
    "loghomes",
    "Domy z kłód",
    "house",
    "Budownictwo",
    "Budowa domów z kłód i kamienia: +5 miejsc na poziom.",
    ["shelters", "logging"],
    { wood: 40, stone: 20 },
    35,
  ),
  d(
    "storage",
    "Magazynowanie",
    "warehouse",
    "Budownictwo",
    "Magazyny oraz możliwość ustawiania rezerw surowców.",
    ["shelters"],
    { wood: 30, stone: 15 },
    25,
  ),
  d(
    "masonry",
    "Obróbka kamienia",
    "brick",
    "Budownictwo",
    "Produkcja kamiennych cegieł u kamieniarza.",
    ["quarrying"],
    { stone: 45, stoneTools: 2 },
    40,
  ),
  d(
    "housing",
    "Ciesielstwo",
    "house",
    "Budownictwo",
    "Domy z desek: +8 miejsc na poziom.",
    ["sawing", "weaving"],
    { planks: 35, rope: 8 },
    65,
  ),
  d(
    "architecture",
    "Architektura",
    "house",
    "Budownictwo",
    "Kamienne domy: +12 miejsc na poziom.",
    ["housing", "masonry", "ironwork"],
    { bricks: 50, knowledge: 40 },
    100,
  ),
  d(
    "hunting",
    "Łowiectwo",
    "tent",
    "Żywność",
    "Łowcy dostarczają skóry i jedzenie.",
    ["stonecraft"],
    { wood: 25, stoneTools: 1 },
    25,
  ),
  d(
    "waterworks",
    "Studnie",
    "well",
    "Żywność",
    "Wydajne pozyskiwanie wody.",
    ["quarrying"],
    { stone: 35, wood: 20 },
    35,
  ),
  d(
    "agriculture",
    "Rolnictwo",
    "farm",
    "Żywność",
    "Uprawa warzyw, zboża i lnu. Nasiona przynoszą wyprawy.",
    ["shelters"],
    { wood: 25, seeds: 2 },
    40,
  ),
  d(
    "weaving",
    "Tkactwo i liny",
    "cloth",
    "Żywność",
    "Len można przetwarzać na tkaniny i liny.",
    ["agriculture", "sawing"],
    { flax: 20, planks: 15 },
    45,
  ),
  d(
    "milling",
    "Młynarstwo",
    "food",
    "Żywność",
    "Młyn i piekarnia: zboże, mąka, chleb.",
    ["agriculture", "sawing"],
    { grain: 30, planks: 20 },
    60,
  ),
  d(
    "herbalism",
    "Zielarstwo",
    "farm",
    "Żywność",
    "Zbieranie ziół i produkcja medykamentów w warsztacie podróżnika.",
    ["hunting", "packing"],
    { knowledge: 15, water: 30 },
    60,
  ),
  d(
    "charcoal",
    "Wypalanie węgla",
    "kiln",
    "Metalurgia",
    "Piece do produkcji węgla drzewnego.",
    ["quarrying", "logging"],
    { wood: 40, stone: 30 },
    40,
  ),
  d(
    "pottery",
    "Garncarstwo",
    "food",
    "Metalurgia",
    "Zbieranie gliny i wypalanie naczyń.",
    ["charcoal"],
    { stone: 25, wood: 25 },
    35,
  ),
  d(
    "mining",
    "Górnictwo",
    "mine",
    "Metalurgia",
    "Kopalnia miedzi. Następne złoża otwierają odkrycia.",
    ["masonry", "weaving"],
    { planks: 25, rope: 5, stoneTools: 3 },
    60,
  ),
  d(
    "copperwork",
    "Hutnictwo miedzi",
    "copper",
    "Metalurgia",
    "Huta i produkcja miedzianych sztabek.",
    ["mining", "charcoal"],
    { copperore: 25, bricks: 20 },
    60,
  ),
  d(
    "bronzework",
    "Brązownictwo",
    "bronze",
    "Metalurgia",
    "Brąz, kuźnia i narzędzia z brązu (wydajność ×2).",
    ["copperwork", "tin"],
    { copper: 20, tinore: 10 },
    70,
  ),
  d(
    "ironwork",
    "Obróbka żelaza",
    "ingot",
    "Metalurgia",
    "Żelazo, węgiel kamienny i narzędzia żelazne (×3).",
    ["bronzework", "learning"],
    { bronze: 30, knowledge: 30 },
    100,
  ),
  d(
    "scouting",
    "Zwiad",
    "tent",
    "Wyprawy i handel",
    "Obóz zwiadowców i pierwsze szlaki.",
    ["shelters"],
    { wood: 20, food: 15 },
    20,
  ),
  d(
    "trade",
    "Handel",
    "bronze",
    "Wyprawy i handel",
    "Kupowanie i sprzedawanie za złoto, zamówienia i reputacja.",
    ["scouting"],
    { wood: 30, food: 20 },
    30,
  ),
  d(
    "packing",
    "Wyposażenie podróżników",
    "hide",
    "Wyprawy i handel",
    "Warsztat plecaków. Plecak daje +25% łupów, narzędzia +15%.",
    ["weaving", "hunting"],
    { cloth: 15, leather: 15 },
    55,
  ),
  d(
    "learning",
    "Piśmiennictwo",
    "book",
    "Wyprawy i handel",
    "Pracownia wytwarzająca wiedzę.",
    ["weaving"],
    { planks: 25, cloth: 10 },
    50,
  ),
  d(
    "cartography",
    "Kartografia",
    "book",
    "Wyprawy i handel",
    "Mapy i wyprawy do odległych ruin.",
    ["learning", "scouting"],
    { knowledge: 20, maps: 1 },
    75,
  ),
  d(
    "organization",
    "Organizacja pracy",
    "person",
    "Wyprawy i handel",
    "+10% tempa wszystkich produkcji i budowy.",
    ["learning", "storage"],
    { knowledge: 30, pottery: 10 },
    75,
  ),
  d(
    "watch",
    "Warta osady",
    "person",
    "Wojsko i obrona",
    "Organizacja nocnych wart i patroli. Otwiera garnizon oraz podstawowe patrole.",
    ["scouting"],
    { wood: 35, stone: 20, food: 20, knowledge: 8 },
    35,
  ),
  d(
    "militia",
    "Milicja osadnicza",
    "person",
    "Wojsko i obrona",
    "Pozwala tworzyć oddziały z mieszkańców i prowadzić wyprawy przeciw szabrownikom.",
    ["watch"],
    { wood: 55, stone: 25, food: 45, knowledge: 18 },
    55,
  ),
  d(
    "bows",
    "Łuki i strzały",
    "tools",
    "Wojsko i obrona",
    "Odblokowuje wyspecjalizowanych łuczników. Wymaga łowiectwa, obróbki drewna i zorganizowanej warty.",
    ["hunting", "sawing", "watch"],
    { planks: 35, leather: 12, knowledge: 15 },
    50,
  ),
  d(
    "spears",
    "Włócznie i tarcze",
    "tools",
    "Wojsko i obrona",
    "Odblokowuje włóczników wyposażonych do obrony bram i utrzymania szyku.",
    ["militia", "stonecraft"],
    { wood: 45, stone: 25, leather: 8 },
    45,
  ),
  d(
    "fortifications",
    "Umocnienia i posterunki",
    "house",
    "Wojsko i obrona",
    "Pozwala zakładać posterunki, które zwiększają bezpieczeństwo szlaków i zasięg działań.",
    ["militia", "masonry"],
    { planks: 70, bricks: 35, rope: 12, knowledge: 28 },
    75,
  ),
  d(
    "military_logistics",
    "Wojskowa logistyka",
    "warehouse",
    "Wojsko i obrona",
    "Lepsze planowanie zapasów skraca operacje i ogranicza straty podczas odwrotu.",
    ["militia", "trade", "cartography"],
    { planks: 80, cloth: 20, maps: 2, knowledge: 40 },
    90,
  ),
  d(
    "iron_arms",
    "Broń i pancerze żelazne",
    "ingot",
    "Wojsko i obrona",
    "Umożliwia wyposażenie oddziałów w żelazną broń i ochronę.",
    ["militia", "ironwork"],
    { iron: 35, tools: 8, knowledge: 45 },
    100,
  ),
  {
    id: "tin",
    name: "Złoże cyny",
    icon: "tinore",
    branch: "Znaleziska i specjaliści",
    description: "Odblokowuje wydobycie cyny w kopalni.",
    requires: ["mining"],
    cost: {},
    duration: 0,
    kind: "find",
    source: "Wyprawa: Skaliste wzgórza",
  },
  {
    id: "carpenter",
    name: "Cieśla",
    icon: "logger",
    branch: "Znaleziska i specjaliści",
    description:
      "+20% tempa pozyskiwania wszystkich gatunków drewna i produkcji desek.",
    requires: ["logging"],
    cost: {},
    duration: 0,
    kind: "specialist",
    source: "Wydarzenie: Cieśla przy ognisku",
    bonus: { buildings: ["logger", "sawmill"], percent: 20 },
  },
  {
    id: "miner",
    name: "Doświadczony górnik",
    icon: "quarry",
    branch: "Znaleziska i specjaliści",
    description: "+20% tempa pracy kamieniarza i kopalni.",
    requires: ["mining"],
    cost: {},
    duration: 0,
    kind: "specialist",
    source: "Wydarzenie: Górnik z dawnych kopalń",
    bonus: { buildings: ["quarry", "mine"], percent: 20 },
  },
  {
    id: "farmer",
    name: "Rolniczka",
    icon: "farm",
    branch: "Znaleziska i specjaliści",
    description: "+20% produkcji gospodarstwa i młyna.",
    requires: ["agriculture"],
    cost: {},
    duration: 0,
    kind: "specialist",
    source: "Wydarzenie: Wiedza o ziemi",
    bonus: { buildings: ["farm", "mill"], percent: 20 },
  },
  {
    id: "merchant",
    name: "Zaufany kupiec",
    icon: "bronze",
    branch: "Znaleziska i specjaliści",
    description: "Ceny zakupu niższe o 15%.",
    requires: ["trade"],
    cost: {},
    duration: 0,
    kind: "specialist",
    source: "Wydarzenie po zdobyciu 3 punktów reputacji",
  },
];
export const expeditions: Expedition[] = [
  {
    id: "path",
    name: "Stary trakt",
    description: "Zapasy, monety i nasiona. Pewny szlak na pierwsze wyprawy.",
    duration: 60,
    cost: { food: 10, water: 5 },
    reward: { wood: 25, stone: 15, gold: 12, seeds: 3, maps: 1 },
    workers: 1,
    requires: "scouting",
  },
  {
    id: "forest",
    name: "Głęboki las",
    description: "Skóry, zioła i cenne gatunki drewna.",
    duration: 120,
    cost: { food: 18, water: 10 },
    reward: { hardwood: 35, leather: 18, herbs: 10, gold: 18 },
    workers: 2,
    requires: "hunting",
  },
  {
    id: "hills",
    name: "Skaliste wzgórza",
    description: "Próbki rud. Pierwsza wyprawa odkrywa złoże cyny.",
    duration: 150,
    cost: { food: 20, water: 15 },
    reward: { copperore: 30, tinore: 20, gold: 25 },
    workers: 2,
    requires: "mining",
    find: "tin",
    gear: { stoneTools: 1 },
  },
  {
    id: "ruins",
    name: "Zapomniane ruiny",
    description:
      "Księgi, relikty i złoto. Mapę zużywasz przy wyjściu; medykamenty są zapasem awaryjnym.",
    duration: 240,
    cost: { food: 30, water: 20, maps: 1, medicine: 2 },
    reward: { knowledge: 35, relics: 2, gold: 60, noblewood: 20 },
    workers: 2,
    requires: "cartography",
    gear: { packs: 1 },
  },
];
export const events: EventDef[] = [
  {
    id: "visitors",
    name: "Wędrowcy we mgle",
    description:
      "Dwoje ludzi prosi o schronienie. Potrzebują miejsca oraz jedzenia na pierwsze dni.",
    after: 45,
    cost: { food: 15, water: 10 },
    people: 2,
  },
  {
    id: "carpenter",
    name: "Cieśla przy ognisku",
    description:
      "Cieśla podzieli się wiedzą w zamian za materiały. Jego nauka daje stałą premię całej gałęzi drewna.",
    requires: "logging",
    after: 60,
    cost: { wood: 30, food: 15 },
    discovery: "carpenter",
  },
  {
    id: "farmer",
    name: "Wiedza o ziemi",
    description:
      "Wędrowna rolniczka uczy mieszkańców skuteczniejszej uprawy i przetwarzania zbiorów.",
    requires: "agriculture",
    after: 120,
    cost: { food: 25, water: 20 },
    discovery: "farmer",
    reward: { seeds: 5 },
  },
  {
    id: "miner",
    name: "Górnik z dawnych kopalń",
    description:
      "Przybysz zna sposoby wydobycia i obróbki skał. Zostawi wiedzę w zamian za zapasy na podróż.",
    requires: "mining",
    after: 180,
    cost: { food: 25, stoneTools: 2 },
    discovery: "miner",
  },
  {
    id: "merchant",
    name: "Zaufanie kupców",
    description:
      "Za wykonane zamówienia kupiec oferuje stały rabat. Wymaga 3 punktów reputacji.",
    requires: "trade",
    after: 180,
    cost: {},
    discovery: "merchant",
  },
  {
    id: "survivors",
    name: "Ocaleni ze starego traktu",
    description:
      "Zwiadowcy wskazali bezpieczną drogę trzem ocalałym. Czekają na decyzję o przyjęciu.",
    requires: "scouting",
    after: 180,
    cost: { food: 25, water: 15 },
    people: 3,
  },
];
export const orders = [
  {
    id: "timber",
    name: "Materiały na most",
    cost: { planks: 30, rope: 8 },
    gold: 70,
    requires: "weaving",
  },
  {
    id: "tools",
    name: "Wyposażenie karawany",
    cost: { stoneTools: 6, food: 30 },
    gold: 60,
    requires: "trade",
  },
  {
    id: "bronze",
    name: "Dostawa do kuźni",
    cost: { bronze: 30, charcoal: 20 },
    gold: 120,
    requires: "bronzework",
  },
];
export const marketGoods: {
  id: Resource;
  buy: number;
  sell: number;
  unlock?: string;
}[] = [
  { id: "wood", buy: 2, sell: 0.5 },
  { id: "stone", buy: 2, sell: 0.5 },
  { id: "food", buy: 2, sell: 0.5 },
  { id: "water", buy: 1, sell: 0.25 },
  { id: "seeds", buy: 5, sell: 1 },
  { id: "planks", buy: 4, sell: 1, unlock: "sawing" },
  { id: "leather", buy: 3, sell: 1, unlock: "hunting" },
  { id: "cloth", buy: 5, sell: 2, unlock: "weaving" },
  { id: "stoneTools", buy: 10, sell: 3, unlock: "stonecraft" },
  { id: "bronzeTools", buy: 30, sell: 10, unlock: "bronzework" },
  { id: "relics", buy: 80, sell: 25, unlock: "cartography" },
];
export const resourceName = (id: string) =>
  resources.find((r) => r.id === id)?.name ?? id;
export const researchName = (id: string) =>
  researches.find((r) => r.id === id)?.name ?? id;
